class InsuranceProviders {
  static const List<String> all = [
    "BPJS Kesehatan",
    "Prudential Indonesia",
    "Allianz Indonesia",
    "Manulife Indonesia",
    "AIA Financial",
    "AXA Mandiri",
    "Cigna Indonesia",
    "Sinarmas MSIG Life",
    "Lippo General Insurance",
    "Asuransi Jasindo",
    "Asuransi Astra (Garda Oto)",
    "Asuransi Sinar Mas",
    "Tugu Insurance",
    "Panin Dai-ichi Life",
    "Sequis Life",
    "Generali Indonesia",
    "Great Eastern Life Indonesia",
    "Avrist Assurance",
    "BNI Life Insurance",
    "Mandiri Inhealth",
    "BRI Life",
    "Zurich Indonesia",
    "Chubb Life Indonesia",
    "Commonwealth Life",
    "Asuransi Adira Dinamika",
    "Asuransi Central Asia (ACA)",
    "Asuransi Bintang",
    "Asuransi Raksa Pratikara",
    "Asuransi Wahana Tata (Aswata)",
    "Sompo Insurance Indonesia",
    "Tokio Marine Indonesia",
  ];
}
