class InsuranceProviders {
  static const List<String> all = [
    "AIA Financial",
    "Allianz Indonesia",
    "Asuransi Adira Dinamika",
    "Asuransi Astra (Garda Oto)",
    "Asuransi Bintang",
    "Asuransi Central Asia (ACA)",
    "Asuransi Jasindo",
    "Asuransi Raksa Pratikara",
    "Asuransi Sinar Mas",
    "Asuransi Wahana Tata (Aswata)",
    "Avrist Assurance",
    "AXA Mandiri",
    "BNI Life Insurance",
    "BPJS Kesehatan",
    "BRI Life",
    "Chubb Life Indonesia",
    "Cigna Indonesia",
    "Commonwealth Life",
    "Generali Indonesia",
    "Great Eastern Life Indonesia",
    "Lippo General Insurance",
    "Mandiri Inhealth",
    "Manulife Indonesia",
    "Panin Dai-ichi Life",
    "Prudential Indonesia",
    "Sequis Life",
    "Sinarmas MSIG Life",
    "Sompo Insurance Indonesia",
    "Tokio Marine Indonesia",
    "Tugu Insurance",
    "Zurich Indonesia",
  ];
}
