// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVkFmgS634G0gRXvEseiW_a164uyw2Lmg',
    appId: '1:171721344232:web:3cf9ee6d9f254be8fc755d',
    messagingSenderId: '171721344232',
    projectId: 'homecare-eb529',
    authDomain: 'homecare-eb529.firebaseapp.com',
    storageBucket: 'homecare-eb529.firebasestorage.app',
    measurementId: 'G-2FWLN3G6PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Fk4kgvPegBNkIyCOcTYJtv9rQdISI_E',
    appId: '1:171721344232:android:a4041be815e63e54fc755d',
    messagingSenderId: '171721344232',
    projectId: 'homecare-eb529',
    storageBucket: 'homecare-eb529.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzX6H7HLhlJpgJn8qUpMQRbKVBKKYVJQE',
    appId: '1:171721344232:ios:6ab948d00997dd87fc755d',
    messagingSenderId: '171721344232',
    projectId: 'homecare-eb529',
    storageBucket: 'homecare-eb529.firebasestorage.app',
    iosBundleId: 'com.intimedicare.homecare.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzX6H7HLhlJpgJn8qUpMQRbKVBKKYVJQE',
    appId: '1:171721344232:ios:6ab948d00997dd87fc755d',
    messagingSenderId: '171721344232',
    projectId: 'homecare-eb529',
    storageBucket: 'homecare-eb529.firebasestorage.app',
    iosBundleId: 'com.intimedicare.homecare.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVkFmgS634G0gRXvEseiW_a164uyw2Lmg',
    appId: '1:171721344232:web:cc9f23f2faad2d5dfc755d',
    messagingSenderId: '171721344232',
    projectId: 'homecare-eb529',
    authDomain: 'homecare-eb529.firebaseapp.com',
    storageBucket: 'homecare-eb529.firebasestorage.app',
    measurementId: 'G-DQH5N7SXGL',
  );
}
